### ISSUE TITLE
Codec issue

### ISSUE THREAD

**Issue by MKastuv** [hSaria/ChromaTerm#88]
# Codec Issue
So, as suggested I used `ssh | ct`. On my remote server I was running weather report `curl wttr.in` but by default, it would pipe through ct. 
I got this error. Any suggestion ?
```bash
  File "/usr/local/bin/ct", line 11, in <module>
    sys.exit(chromaterm.main(chromaterm.config_init()))
  File "/usr/local/lib/python3.7/dist-packages/chromaterm/__init__.py", line 507, in main
    buffer += data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 4095: unexpected end of data
```

**Comment by hSaria** [comment]
It seems that you're running a much older version of ChromaTerm (v0.4.8 if I'm not mistaken). You should upgrade to the latest with `pip3 install -U chromaterm`.

**Comment by MKastuv** [comment]
I think I have already upgraded it ... 
```
$ pip freeze | grep chromaterm
chromaterm==0.6.2  
$ curl wttr.in | ct
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Traceback (most recent call last):
  File "/usr/local/bin/ct", line 7, in <module>
    import chromaterm.misc
ModuleNotFoundError: No module named 'chromaterm.misc'
 48  8566   48  4147    0     0  16136      0 --:--:-- --:--:-- --:--:-- 16136
curl: (23) Failed writing body (2845 != 2896)
```

**Comment by MKastuv** [comment]
It worked ... I upgraded in pip3 but it was working through old pip version 0.4.8. I uninstalled from pip. Thanks !
